<div class="template">
    <h1><?= $block->getCustomerCount() ?></h1>
</div>

<div class="customer-list">
    <table>
        <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Email</th>
        </tr>
        <?php foreach ($this->getCustomerList() as $product) : ?>
            <tr>
                <td><?= $product->getFirstName()?></td>
                <td><?= $product->getLastName()?></td>
                <td><?= $product->getEmail()?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>